# Verwenden Sie das offizielle MySQL-Image
FROM mysql:8.0

# Setzen Sie Umgebungsvariablen für MySQL
ENV MYSQL_ROOT_PASSWORD=
ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# Exponieren Sie den MySQL-Port
EXPOSE 3306