title: Onleihe Checker
description: Chrome Extension für deutsche digitale Bibliotheken
baseurl: "/onleihe-checker"
url: "https://vaupunkt.github.io"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

lang: de

# Custom settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
